name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    steps:
      - uses: actions/checkout@v3
      
      - uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          deploy_folder: dist/hello-ci-cd/browser
          production: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.MY_SITE_ID }}
